spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO


management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: "test | dev | test-auth"

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: codurance
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    com.codurance.allaboard: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true
---
server:
  servlet:
    context-path: "/api/v1"
  port: 5000

spring:
  profiles:
    active: prod