name: All aboard API - Destroy

on: 
  repository_dispatch:
    types: destroy

jobs:
  manual_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Delete Elastic Beanstalk application
        run: |
          aws elasticbeanstalk delete-application --application-name all-aboard-api --terminate-env-by-force
