# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: All aboard API - Infra as code

on: repository_dispatch

jobs:
  manual_deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create an ElasticBeanstalk application
        run: |
          aws elasticbeanstalk create-application \
          --application-name all-aboard-api \
          --description "All Aboard backend API" \
          --tags Key=name,Value=all-aboard-api

      - name: Create an ElasticBeanstalk configuration template
        run: |
          aws elasticbeanstalk create-configuration-template \
          --application-name all-aboard-api \
          --template-name ${{ github.sha }} \
          --solution-stack-name "64bit Amazon Linux 2 v3.1.3 running Corretto 11" \
          --tags Key=name,Value=all-aboard-api

      - name: Create an ElasticBeanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name all-aboard-api \
          --version-label "ver-${{ github.sha }}"
          --description "commit-sha-${{ github.sha }}"

      - name: Create an ElasticBeanstalk environment
        run: |
          aws elasticbeanstalk create-environment \
            --application-name all-aboard-api \
            --template-name ${{ github.sha }} \
            --environment-name all-aboard-api-dev \
            --version-label ${{ github.sha }} \
            --option-settings Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=aws-elasticbeanstalk-ec2-role