# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@1.1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

#    - name: Run tests with Maven
#      run: mvn clean test

    - name: Packaging with Maven
      run: mvn package

    - name: Create ZIP deployment package
      run: zip -r deploy.zip ./target/**jar

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-west-1"

    - name: Upload package to S3 bucket
      run: aws s3 cp "ver-${{ github.sha }}".zip s3://all-aboard-be/

    - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name all-aboard-be \
          --source-bundle S3Bucket="all-aboard-be",S3Key="ver-${{ github.sha }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

    - name: Deploy new ElasticBeanstalk Application Version
      run: aws elasticbeanstalk update-environment --environment-name all-aboard-be-dev --version-label "ver-${{ github.sha }}"